extapi.go
rcmgr.go

this is typically a user action, so prevent them from being garbage collected
and losing their limit.

make protocols and peers sticky when setting their limit

---

limit_config.go

This is to avoid extra complexity in consumers that expose this config
to users through other means or want to build the config
programmatically, but are currently required to redefine these structs
and keep them in sync. The coupling is already there, we might as well
export these structs and reduce maintenance costs.

feat: export basic limiter config

---

extapi.go
rcmgr.go

This member variable is shadowing the `name` of the embedded `resourceScope`.

fix shadowing of service name

---

trace.go

This happens when empty sub-scopes are moved around between scopes.

skip events that don't change anything in tracer

---

trace.go

RFC3339 only exports up to second granularity, which is not enough for a detailed analysis.

trace exact timestamps

---

trace.go

So that we can easily parse the JSON object from other packages.

export the TraceEvt

---

limit_defaults.go

This is useful when recording a trace to observe the baseline resource consumption.

add a DefaultLimitConfig with infinite limits

---

scope.go

Otherwise two spans on the same resource scope will end up having the same name.

add an ID to spans

---

error.go
scope.go

Fixes #26.
Potentially controversial: also removes the `stat` from the debug output, to focus on the thing that is actually getting blocked. We can add it back if preferred.

include current limits in debug messages

---

trace.go

This is a different implementation of #45, that leaves the name of a scope a string. Instead, when tracing, we parse the name and determine the scope.
Closes #45.

trace the scope as a JSON object

---

limit.go
limit_defaults.go
limit_test.go
rcmgr.go
rcmgr_test.go

Extends on #48 to allow configuring the limits for the allowlist. By default they are the same as the system limits.
Also remember that the allowlist isn't hit unless the system/transient have reached their limits.
Only the commits after 1d67ac4e20cb1ec41e6f3543494bebed64cc908a should be reviewed. The rest are from #48 or a merge commit.
Before merge:

Add ability to configure allowlist limits

---

sys_not_unix.go
sys_windows.go

Apparently Windows doesn't limit the number of file descriptors as Linux does. Therefore there's also no way to get the current limit.

don't limit the number of FDs on Windows when autoscaling

---

allowlist_test.go
rcmgr.go
rcmgr_test.go

* Adds an example on how to use the with allowlisted multiaddr option.
* Adds a function that lets you get the allowlist object from the resource manager. Maybe this should be part of the core api, or maybe NewResourceManager should return a concrete type. I think it'll be easier to change this in a monorepo, but this should be work for now. It should be a small number of users using this right now.

Add docs around WithAllowlistedMultiaddrs. Expose allowlist

---

obs/stats_test.go
rcmgr_test.go
trace.go

Fixes a subtle bug where we assumed we would always have a background task when we have a trace object. This would cause `trace.Close()` to hang indefinitely.
The fix is to use a waitgroup instead of a semaphore channel. Then we add to the waitgroup when we spawn a background task.

Don't wait for a chan that will never close

---

limit_config_test.go
limit_defaults.go

Fixes a bug where we would output the json with the raw peer id rather than the encoded version. This would mean would aren't able to round trip serialize the config. e.g. take the config, write it json, read it from json and compare it with the original config.
This uses the type alias marshaling trick. More can info about this can be found at https://calvinfeng.gitbook.io/gonotebook/idioms/custom-json-marshaling#better-approach (and many other sources).

Implement `json.Marshaler` interface for LimitConfig

---

obs/grafana-dashboards/README.md
obs/grafana-dashboards/resource-manager.json

I made the mistake of not using the "exported" version of this JSON dashboard. The exported version contains a datasource field so that users can specify their prometheus source.
I also updated the readme with instructions on how to update this json file.

Use templated version of grafana dashboard json

---

obs/grafana-dashboards/resource-manager.json

I assumed a single instance, but deploying this on a cluster showed me we want to surface the instances in the chart.
Users can add an ad hoc filter in the dashboard to filter to a specific instance as well (this doesn't transfer well in the template).

feat: Handle multiple instances in stock grafana dashboard

---

obs/grafana-dashboards/resource-manager.json

Aggregates the memory stats across all selected instances in the stock dashboard. I considered adding a "instance" label, but things looked pretty messy.
Before:
After:

Simplify mem graphs in stock grafana dashboard

---

obs/stats.go

Adds another tag to record if the blocked thing was an inbound or outbound thing

Record which direction the resource was blocked

---

obs/stats.go
obs/stats_test.go

Fixes a silly mistake that results in a null pointer error since we're creating zero value objects. This happened because I originally was going to set the items in the array, but then decided to use `append` instead. Adds a test for regression too.

Fix usage of make to reserve capacity, not values

---

obs/grafana-dashboards/README.md
obs/grafana-dashboards/resource-manager.json
obs/stats.go

This adds the "rcmgr_" prefix to the exposed metrics.
I originally thought we could add a namespace when we registered the exporter, but it turns out that was done on a more global level rather than just for these sets of metrics.
e.g.:
```go
_, err = ocprom.NewExporter(ocprom.Options{
Registry: prometheus.DefaultRegisterer.(*prometheus.Registry),
Namespace: "some_namespace", // This sets the global namespace to all opencensus metrics. I originally thought it was only for the specified metrics.
})
```
This also updates the dashboard to use the new name. If users add their own namespace to the exporter they'll have to update the dashboard before importing.

Add namespace to metrics
